#!/bin/bash

SCRIPT_DIR="$(dirname $0)"
wget -N -q -P $SCRIPT_DIR https://javacc.com/download/javacc.jar || true 
wget -N -q -P $SCRIPT_DIR https://javacc.com/download/freemarker.jar || true

java -jar "$SCRIPT_DIR/javacc.jar" "$@"
