/* Generated by: ${generated_by}. ${filename} */
[#if grammar.options.userDefinedLexer]
  [#if grammar.parserPackage?has_content]
    package ${grammar.parserPackage};
  [/#if]

/**
 * An implementation for this interface is generated by
 * JavaCCParser.  The user is free to use any implementation
 * of their choice.
 */

public interface Lexer {

  /** This gets the next token from the input stream.
   *  A token of kind 0 (<EOF>) should be returned on EOF.
   */
  public Token getNextToken();


  /** 
   * This returns a string that says where the 
   * Tokens are coming from. This will typically be 
   * a filename.
   */
  String getInputSource();

}
[#else]
[#embed "LexGen.java.ftl"] 
[/#if]
