[#ftl strict_vars=true]
[#--
/* Copyright (c) 2020, 2021 Jonathan Revusky, revusky@javacc.com
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notices,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary formnt must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name Jonathan Revusky
 *       nor the names of any contributors may be used to endorse 
 *       or promote products derived from this software without specific prior written 
 *       permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
 --]
/* Generated by: ${generated_by}. ${filename} */

[#if grammar.parserPackage?has_content]
package ${grammar.parserPackage};
[/#if]

import java.io.IOException;
import java.io.Reader;
import java.util.HashMap;
import java.util.Map;


/**
 * Rather bloody-minded implementation of a class to read in a file 
 * and store the contents in a String, and keep track of where the 
 * lines are.
 */
@SuppressWarnings("unused")
public class FileLineMap {

    private static final int[] EMPTY_INT = new int[0];

    static private Map<String, FileLineMap> mapsByName = new HashMap<>();

    /**
     * Get a FileLineMap by name
     */
    static public FileLineMap getFileLineMapByName(String name) {
        return mapsByName.get(name);
    }

    /**
     * This class maintains a lookup table of all the FileLineMap objects by name.
     * A long-running process that reads in and parses a lot of different files 
     * might choose to clear that map to make this data subject to garbage collection.
     */
    static public void clearFileLineMaps() {
        mapsByName.clear();
    }

    // Munged content, possibly replace unicode escapes, tabs, or CRLF with LF.
    private final CharSequence content;
    // Typically a filename, I suppose.
    private String inputSource;
    // A list of offsets of the beginning of lines
    private final int[] lineOffsets;
    private int startingLine, startingColumn;
    private int bufferPosition, tokenBeginOffset, tokenBeginColumn, tokenBeginLine, line, column;
    
    [#var TABS_TO_SPACES = 0, PRESERVE_LINE_ENDINGS="true", JAVA_UNICODE_ESCAPE="false"]
    [#if grammar.settings.TABS_TO_SPACES??]
       [#set TABS_TO_SPACES = grammar.settings.TABS_TO_SPACES]
    [/#if]
    [#if grammar.settings.PRESERVE_LINE_ENDINGS?? && !grammar.settings.PRESERVE_LINE_ENDINGS]
       [#set PRESERVE_LINE_ENDINGS = "false"]
    [/#if]
    [#if grammar.settings.JAVA_UNICODE_ESCAPE?? && grammar.settings.JAVA_UNICODE_ESCAPE]
       [#set JAVA_UNICODE_ESCAPE = "true"]
    [/#if]
    public FileLineMap(String inputSource, Reader reader, int startingLine, int startingColumn) {
        this(inputSource, readToEnd(reader), startingLine, startingColumn);
    }

    public FileLineMap(String inputSource, CharSequence content) {
        this(inputSource, content, 1, 1);
    }

    public FileLineMap(String inputSource, CharSequence content, int startingLine, int startingColumn) {
        this.inputSource = inputSource;
        this.content = mungeContent(content, ${TABS_TO_SPACES}, ${PRESERVE_LINE_ENDINGS}, ${JAVA_UNICODE_ESCAPE});
        this.lineOffsets = createLineOffsetsTable(this.content);
        this.setStartPosition(startingLine, startingColumn);
        mapsByName.put(inputSource, this);
   }
    
   
    // START API methods

    // Now some methods to fulfill the functionality that used to be in that
    // SimpleCharStream class
    // This backup() method is dead simple by design and does not handle any of the messiness
    // with column numbers relating to tabs or unicode escapes. 
    public void backup(int amount) {
        for (int i = 0; i < amount; i++) {
            --bufferPosition;
            if (column == 1) {
                --line;
                column = getLineLength(line);
            } else {
                --column;
            }
        }
    }
    
    void forward(int amount) {
        for (int i=0; i<amount; i++) {
            ++bufferPosition;
            if (column < getLineLength(line)) {
                column++;
            } else {
                ++line;
                column =1;
            }
        }
    }
    
    int readChar() {
        if (bufferPosition >= content.length()) {
            return -1;
        }
        int ch = content.charAt(bufferPosition++);
        if (ch == '\n') {
            ++line;
            column = 1;
        } else {
            ++column;
        }
        return ch;
    }

    String getImage() {
        return content.subSequence(tokenBeginOffset, bufferPosition).toString();
    }

    String getSuffix(final int len) {
        int startPos = bufferPosition - len + 1;
        return content.subSequence(startPos, bufferPosition).toString();
    }

    int beginToken() {
        tokenBeginOffset = bufferPosition;
        tokenBeginColumn = column;
        tokenBeginLine = line;
        return readChar();
    }

    int getBeginColumn() {
        return tokenBeginColumn;
    }

    int getBeginLine() {
        return tokenBeginLine;
    }

    int getEndColumn() {
        if (column == 1) {
            if (line == tokenBeginLine) {
                return 1;
            }
            return getLineLength(line - 1);
        }
        return column - 1;
    }

    int getEndLine() {
        if (column == 1 && line > tokenBeginLine)
            return line - 1;
        return line;
    }

    // But there is no goto in Java!!!
    void goTo(int line, int column) {
        this.bufferPosition = getOffset(line, column);
        this.line = line;
        this.column = column;
    }
    
    // END API methods

    private int getLineLength(int lineNumber) {
        int startOffset = getLineStartOffset(lineNumber);
        int endOffset = getLineEndOffset(lineNumber);
        return endOffset - startOffset;
    }

    private int getLineStartOffset(int lineNumber) {
        int realLineNumber = lineNumber - startingLine;
        if (realLineNumber<0) realLineNumber = 0; //REVISIT later
        return lineOffsets[realLineNumber];
    }

    private int getLineEndOffset(int lineNumber) {
        int realLineNumber = lineNumber - startingLine;
        int endOffset = (realLineNumber + 1 == lineOffsets.length) ? content.length() : lineOffsets[realLineNumber + 1];
        return endOffset;
    }

    private void setStartPosition(int line, int column) {
        this.startingLine = line;
        this.startingColumn = column;
        this.line = line;
        this.column = column;
    }

    private int getOffset(int line, int column) {
        if (line==0) line = startingLine; // REVISIT? This should not be necessary!
        int columnAdjustment = (line == startingLine) ? startingColumn : 1;
        return lineOffsets[line - startingLine] + column - columnAdjustment;
    }
    
    // ------------- private utilities method

    // Icky method to handle annoying stuff. Might make this public later if it is
    // needed elsewhere
    private static CharSequence mungeContent(CharSequence content, int tabsToSpaces, boolean preserveLines,
            boolean javaUnicodeEscape) {
        if (tabsToSpaces <= 0 && preserveLines && !javaUnicodeEscape)
            return content;
        StringBuilder buf = new StringBuilder();
        int index = 0;
        int col = 0;
        // This is just to handle spaces to tabs. If you don't have that setting set, it
        // is really unused.
        while (index < content.length()) {
            char ch = content.charAt(index++);
            if (ch == '\\' && javaUnicodeEscape && index < content.length()) {
                ch = content.charAt(index++);
                if (ch != 'u') {
                    buf.append((char) '\\');
                    buf.append(ch);
                    if (ch == '\n')
                        col = 0;
                    else
                        col += 2;
                } else {
                    while (content.charAt(index) == 'u') {
                        index++;
                        // col++;
                    }
                    String hex = content.subSequence(index, index += 4).toString();
                    buf.append((char) Integer.parseInt(hex, 16));
                    // col +=6;
                    ++col;
                    // We're not going to be trying to track line/column information relative to the original content
                    // with tabs or unicode escape, so we just increment 1, not 6
                }
            } else if (ch == '\r' && !preserveLines) {
                buf.append((char) '\n');
                if (index < content.length()) {
                    ch = content.charAt(index++);
                    if (ch != '\n') {
                        buf.append(ch);
                        ++col;
                    } else
                        col = 0;
                }
            } else if (ch == '\t' && tabsToSpaces > 0) {
                int spacesToAdd = tabsToSpaces - col % tabsToSpaces;
                for (int i = 0; i < spacesToAdd; i++) {
                    buf.append((char) ' ');
                    col++;
                }
            } else {
                buf.append((char) ch);
                if (ch == '\n') {
                    col = 0;
                } else
                    col++;
            }
        }
        return buf.toString();
    }

    private static int[] createLineOffsetsTable(CharSequence content) {
        if (content.length() == 0) {
            return EMPTY_INT;
        }
        int lineCount = 0;
        char ch;
        int length = content.length();
        for (int i = 0; i < length; i++) {
            ch = content.charAt(i);
            if (ch == '\n') {
                lineCount++;
            }
        }
        if (content.charAt(length - 1) != '\n') {
            lineCount++;
        }
        int[] lineOffsets = new int[lineCount];
        lineOffsets[0] = 0;
        int index = 1;
        for (int i = 0; i < length; i++) {
            ch = content.charAt(i);
            if (ch == '\n') {
                if (i + 1 == length)
                    break;
                lineOffsets[index++] = i + 1;
            }
        }
        return lineOffsets;
    }


    public String getInputSource() {
        return inputSource;
    }
    
    void setInputSource(String inputSource) {
        mapsByName.put(inputSource, this);
        this.inputSource = inputSource;
    }
    
    // ------------- TODO: unused method for the moment....
    private int getLineCount() {
        return lineOffsets.length;
    }

    String getText(int beginLine, int beginColumn, int endLine, int endColumn) {
        int startOffset = getOffset(beginLine, beginColumn);
        int endOffset = getOffset(endLine, endColumn);
        return getText(startOffset, endOffset);
    }

    private String getText(int startOffset, int endOffset) {
        return content.subSequence(startOffset, endOffset+1).toString();
    }

    private String getLine(int lineNumber) {
        int realLineNumber = lineNumber - startingLine;
        int startOffset = lineOffsets[realLineNumber];
        int endOffset = (realLineNumber + 1 == lineOffsets.length) ? content.length() : lineOffsets[realLineNumber + 1];
        return getText(startOffset, endOffset);
    }

    private int getLineNumber(int offset) {
        int i = 0;
        while (offset >= lineOffsets[i++]) {
            if (i == lineOffsets.length)
                break;
        }
        return i + startingLine - 1;
    }

    static private int BUF_SIZE = 0x10000;

    // Annoying kludge really...
    static private String readToEnd(Reader reader) {
        try {
            return readFully(reader);
        } catch (IOException ioe) {
            throw new RuntimeException(ioe);
        }
    }

    static String readFully(Reader reader) throws IOException {
        char[] block = new char[BUF_SIZE];
        int charsRead = reader.read(block);
        if (charsRead < 0) {
            throw new IOException("No input");
        } else if (charsRead < BUF_SIZE) {
            char[] result = new char[charsRead];
            System.arraycopy(block, 0, result, 0, charsRead);
            reader.close();
            return new String(block, 0, charsRead);
        }
        StringBuilder buf = new StringBuilder();
        buf.append(block);
        do {
            charsRead = reader.read(block);
            if (charsRead > 0) {
                buf.append(block, 0, charsRead);
            }
        } while (charsRead == BUF_SIZE);
        reader.close();
        return buf.toString();
    }
}
