/* Generated by: JavaCC 21 Parser Generator. Do not edit. AndExpression.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class AndExpression extends Expression {
}
