/* Generated by: JavaCC 21 Parser Generator. Do not edit. CaseStatement.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class CaseStatement extends BaseNode {
    // If the case statement has an unreachable break statement at the
    // end, we remove it. This allows us to get rid of this horrid longstanding kludge
    public void close() {
        if (getChildCount()>=2) {
            Node last=this.getLastChild();
            Node secondLast=this.getChild(getChildCount()-2);
            if ((last instanceof BreakStatement)&&(secondLast instanceof ReturnStatement)) {
                removeChild(last);
            }
        }
    }

}
