/* Generated by: JavaCC 21 Parser Generator. Do not edit. CatchBlock.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class CatchBlock extends BaseNode {
    public CodeBlock getBlock() {
        return firstChildOfType(CodeBlock.class);
    }

}
