/* Generated by: JavaCC 21 Parser Generator. Do not edit. CharacterList.java */
package com.javacc.parser.tree;

import java.util.*;

import com.javacc.lexgen.*;
import com.javacc.parser.*;
@SuppressWarnings("unused")
public class CharacterList extends RegularExpression {
    public List<CharacterRange>getDescriptors() {
        return childrenOfType(CharacterRange.class);
    }

    public boolean isNegated() {
        for (Node n : children) {
            if (n instanceof Token) {
                Token t=(Token) n;
                if (t.getId()==JavaCCConstants.TILDE) {
                    return true;
                }
            }
        }
        return false;
    }

}
