/* Generated by: JavaCC 21 Parser Generator. Do not edit. CharacterRange.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class CharacterRange extends BaseNode {
    public char left,right;
    public boolean isSingleChar() {
        return left==right;
    }

}
