/* Generated by: JavaCC 21 Parser Generator. Do not edit. ContinueStatement.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class ContinueStatement extends BaseNode {
}
