/* Generated by: JavaCC 21 Parser Generator. Do not edit. EndOfFile.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class EndOfFile extends com.javacc.lexgen.RegularExpression {
}
