/* Generated by: JavaCC 21 Parser Generator. Do not edit. ExplicitLookahead.java */
package com.javacc.parser.tree;

import com.javacc.parsegen.Lookahead;
import com.javacc.parser.*;
@SuppressWarnings("unused")
public class ExplicitLookahead extends Lookahead {
}
