/* Generated by: JavaCC 21 Parser Generator. Do not edit. FormalParams.java */
package com.javacc.parser.tree;

import java.util.List;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class FormalParams extends BaseNode {
    public List<FormalParameter>getParams() {
        return childrenOfType(FormalParameter.class);
    }

    public String getAsString() {
        StringBuilder buf=new StringBuilder();
        List<FormalParameter>params=getParams();
        boolean first=true;
        for (FormalParameter param : params) {
            if (!first) {
                buf.append(", ");
            }
            buf.append(param.getAsString());
            first=false;
        }
        return buf.toString();
    }

    public String toString() {
        StringBuilder buf=new StringBuilder();
        for (Token tok : Nodes.getRealTokens(this)) {
            buf.append(" ");
            buf.append(tok);
        }
        return buf.toString();
    }

}
