/* Generated by: JavaCC 21 Parser Generator. Do not edit. HashID.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class HashID extends Token {
    public HashID(int kind,String image) {
        super(kind,image);
    }

}
