/* Generated by: JavaCC 21 Parser Generator. Do not edit. Identifier.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class Identifier extends Token {
    public String getNormalizedText() {
        String image=getRawText();
        if (image.equals("jjtThis")||image.equals("CURRENT_NODE")) {
            return getGrammar().getCurrentNodeVariableName();
        }
        if (image.equals("PARSER_CLASS")) {
            return getGrammar().getParserClassName();
        }
        if (image.equals("LEXER_CLASS")) {
            return getGrammar().getLexerClassName();
        }
        if (image.equals("CONSTANTS_CLASS")) {
            return getGrammar().getConstantsClassName();
        }
        if (image.equals("NODE_PACKAGE")) {
            return getGrammar().getNodePackage();
        }
        if (image.equals("PARSER_PACKAGE")) {
            return getGrammar().getParserPackage();
        }
        return image;
    }

    public Identifier(int kind,String image) {
        super(kind,image);
    }

}
