/* Generated by: JavaCC 21 Parser Generator. Do not edit. JavaCCKeyWord.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class JavaCCKeyWord extends Token {
    public JavaCCKeyWord(int kind,String image) {
        super(kind,image);
    }

}
