/* Generated by: JavaCC 21 Parser Generator. Do not edit. KeyWord.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class KeyWord extends Token {
    public KeyWord(int kind,String image) {
        super(kind,image);
    }

}
