/* Generated by: JavaCC 21 Parser Generator. Do not edit. MemberValueArrayInitializer.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class MemberValueArrayInitializer extends BaseNode {
}
