/* Generated by: JavaCC 21 Parser Generator. Do not edit. MethodDeclaration.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class MethodDeclaration extends BaseNode {
    public String getName() {
        for (Node n : children) {
            if (n instanceof Identifier) {
                return n.toString();
            }
        }
        throw new IllegalStateException();
    }

    public FormalParams getFormalParams() {
        return firstChildOfType(FormalParams.class);
    }

    public String getFullSignature() {
        return getName()+getFormalParams();
    }

}
