/* Generated by: JavaCC 21 Parser Generator. Do not edit. Name.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class Name extends BaseNode {
    public String toString() {
        StringBuilder buf=new StringBuilder();
        for (Token tok : Nodes.getRealTokens(this)) {
            buf.append(tok);
        }
        return buf.toString();
    }

}
