/* Generated by: JavaCC 21 Parser Generator. Do not edit. ReturnType.java */
package com.javacc.parser.tree;

import java.util.List;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class ReturnType extends BaseNode implements freemarker.template.TemplateBooleanModel {
    public boolean getAsBoolean() {
        List<Token>lt=Nodes.getRealTokens(this);
        return lt.size()!=1||lt.get(0).getId()!=VOID;
    }

}
