/* Generated by: JavaCC 21 Parser Generator. Do not edit. TernaryExpression.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class TernaryExpression extends Expression {
}
