/* Generated by: JavaCC 21 Parser Generator. Do not edit. ThrowsList.java */
package com.javacc.parser.tree;

import java.util.ArrayList;
import java.util.List;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class ThrowsList extends BaseNode {
    public List<Node>getTypes() {
        List<Node>result=new ArrayList<Node>();
        for (Node n : children) {
            if ((n instanceof Name)||(n instanceof Identifier)) {
                result.add(n);
            }
        }
        return result;
    }

}
