/* Generated by: JavaCC 21 Parser Generator. Do not edit. TryBlock.java */
package com.javacc.parser.tree;

import java.util.List;

import com.javacc.lexgen.TokenSet;
import com.javacc.parsegen.Expansion;
import com.javacc.parser.*;
@SuppressWarnings("unused")
public class TryBlock extends Expansion {
    public Expansion getNestedExpansion() {
        return firstChildOfType(Expansion.class);
    }

    public List<CatchBlock>getCatchBlocks() {
        return childrenOfType(CatchBlock.class);
    }

    public FinallyBlock getFinallyBlock() {
        return firstChildOfType(FinallyBlock.class);
    }

    public boolean isPossiblyEmpty() {
        return getNestedExpansion().isPossiblyEmpty();
    }

    public TokenSet getFirstSet() {
        return getNestedExpansion().getFirstSet();
    }

    public TokenSet getFinalSet() {
        return getNestedExpansion().getFinalSet();
    }

    public boolean requiresPhase2Routine() {
        return getNestedExpansion().requiresPhase2Routine();
    }

    public int minimumSize(int min) {
        return getNestedExpansion().getMinimumSize();
    }

}
