/* Generated by: JavaCC 21 Parser Generator. Do not edit. TypeParameterList.java */
package com.javacc.parser.tree;

import java.util.*;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class TypeParameterList extends BaseNode {
    public void add(TypeParameter param) {
        if (!getParameters().contains(param)) {
            ListIterator<Node>iterator=iterator();
            while (iterator.hasNext()) {
                iterator.next();
            }
            iterator.previous();
            iterator.add(Token.newToken(COMMA,","));
            iterator.next();
            iterator.add(param);
        }
    }

    public void add(TypeParameterList params) {
        for (TypeParameter param : params.getParameters()) {
            add(param);
        }
    }

    public List<TypeParameter>getParameters() {
        return childrenOfType(TypeParameter.class);
    }

}
