/* Generated by: JavaCC 21 Parser Generator. Do not edit. WhileStatement.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class WhileStatement extends BaseNode {
}
