/* Generated by: JavaCC 21 Parser Generator. Do not edit. WildcardBounds.java */
package com.javacc.parser.tree;

import com.javacc.parser.*;
@SuppressWarnings("unused")
public class WildcardBounds extends BaseNode {
}
