/* Generated by: JavaCC 21 Parser Generator. Do not edit. ZeroOrMoreRegexp.java */
package com.javacc.parser.tree;

import com.javacc.lexgen.RegularExpression;
import com.javacc.parser.*;
@SuppressWarnings("unused")
public class ZeroOrMoreRegexp extends RegularExpression {
    public RegularExpression getRegexp() {
        return firstChildOfType(RegularExpression.class);
    }

    public void setRegexp(RegularExpression regexp) {
        RegularExpression current=getRegexp();
        if (current!=null) {
            addChild(indexOf(current),regexp);
            removeChild(current);
        }
        else {
            addChild(1,regexp);
        }
    }

}
