/* Generated by: ${generated_by}. Do not edit. ${filename} */
[#if grammar.parserPackage?has_content]
package ${grammar.parserPackage};
[/#if]

import java.io.IOException;
import java.io.Reader;

/**
 * Token literal values and constants.
 */

  public interface ${grammar.constantsClassName} {

  public enum TokenType {
     [#list grammar.lexerData.regularExpressions as regexp]
       ${regexp.label},
     [/#list]
     [#list grammar.extraTokenNames as extraToken]
       ${extraToken},
     [/#list]
     INVALID
  }
  
  /**
   * Lexical States
   */

  public enum LexicalState {
  [#list grammar.lexerData.lexicalStates as lexicalState]
     ${lexicalState.name},
  [/#list]
   }
}

