name: C# Generation Tests

on:
  push:
    branches: [ master, ci-changes ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Wait to resolve Windows issues
        # os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [ubuntu-20.04, macos-latest]
        java-version: ['8', '11', '16', '17']
        dotnet-version: ['5.0.x']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Create test directories (POSIX)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        mkdir -p ~/bin ~/logs
    - name: Create test directories (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $dirs = "${env:USERPROFILE}/bin", "${env:USERPROFILE}/logs"
        foreach ($d in $dirs) {
          if (!(test-path $d)) {
            mkdir $d
          }
        }
    - name: Setup IronPython 2.7.11 (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: |
        pwd
        echo ==================
        ls -l
        echo ==================
        wget -q https://github.com/IronLanguages/ironpython2/releases/download/ipy-2.7.11/ironpython_2.7.11.deb -O ironpython_2.7.11.deb
        sudo dpkg -i ironpython_2.7.11.deb
    - name: Setup IronPython 2.7.11 (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        pwd
        echo ==================
        ls -l
        echo ==================
        wget -q https://github.com/IronLanguages/ironpython2/releases/download/ipy-2.7.11/IronPython-2.7.11.pkg -O IronPython-2.7.11.pkg
        sudo installer -pkg IronPython-2.7.11.pkg -target /
    - name: Setup IronPython 2.7.11 (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        choco install --no-progress mono
        choco install --no-progress ironpython --version=2.7.11
    - name: Cache Jython (POSIX)
      if: ${{ (matrix.os != 'windows-latest') }}
      id: cache-jython-posix
      uses: actions/cache@v2
      with:
        path: ~/bin/jython.jar
        key: ${{ runner.os }}-jython
    - name: Setup Jython 2.7.2 (POSIX)
      if: ${{ (matrix.os != 'windows-latest') && (steps.cache-jython-posix.outputs.cache-hit != 'true') }}
      run: |
        wget https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar -O ~/bin/jython.jar
    - name: Cache Jython (Windows)
      if: ${{ (matrix.os == 'windows-latest') }}
      id: cache-jython-windows
      uses: actions/cache@v2
      with:
        path: ${env:USERPROFILE}/bin/jython.jar
        key: ${{ runner.os }}-jython
    - name: Setup Jython 2.7.2 (Windows)
      # Windows cache check temporarily disabled, as on Windows you can't restore to the correct location
      #if: ${{ matrix.os == 'windows-latest' && (steps.cache-jython-windows.outputs.cache-hit != 'true') }}
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $source = 'https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar'
        $destination = "${env:USERPROFILE}/bin/jython.jar"
        Invoke-WebRequest -Uri $source -OutFile $destination
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run tests
      run: |
        java -jar $HOME/bin/jython.jar --version
        ant -version
        python --version
        ant test-csharp
      env:
        PY_DEBUG: 1
